export const POSTS ='https://jsonplaceholder.typicode.com/posts'
export const BASE_URL ='http://localhost:5000/api'
export const STORE_POST =BASE_URL +`/createPost`
export const GET_ALL_POST =BASE_URL+'/getAllPost'
export const UPDATE_POST =BASE_URL +'/updateById'
export const DELETE_POST =BASE_URL +'/deleteById'
export const UPLOAD_IMAGE=BASE_URL+'/uploadImage'
export const IMAGE_URL ='http://localhost:5000'
export const REGISTER =BASE_URL+ '/admin/register'
export const LOGIN =BASE_URL +'/admin/login'
export const VERIFY_USER=BASE_URL+'/admin/checkUser'
export const LIKE_POST=BASE_URL + '/likePost'
export const GET_COMMENTS =BASE_URL +'/comments/getComment'
export const POST_COMMENTS = BASE_URL+"/comments/postComment"
export const GET_SERACH_POST =BASE_URL +"/searchPost"
export const GET_ALL_USER =BASE_URL+'/admin/getAllUser'
export const SEND_MESSAGE =BASE_URL +'/message/sendMessage'
export const GET_MESSAGE =BASE_URL +'/message/getMessage'
export const SERVER ='http://localhost:5000'
